import type { CarItem } from "@/types/car";

export const INITIAL_CARS: Omit<CarItem, "id">[] = [
  {
    make: "Mercedes-Benz",
    model: "G-Class G63 AMG",
    year: 2024,
    price: 1200000,
    mileage: 0,
    fuel: "Petrol",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1601362840469-51e4d8d58785?auto=format&fit=crop&q=80&w=800",
    type: "SUV",
    featured: true,
    mostWanted: true,
    description: "The legendary G-Wagon with ultimate luxury and performance.",
    engine: "4000 cc",
    shipping: "By Sea Shipping",
    status: "Available",
  },
  {
    make: "Porsche",
    model: "911 GT3 RS",
    year: 2023,
    price: 1450000,
    mileage: 1200,
    fuel: "Petrol",
    transmission: "PDK",
    image: "https://images.unsplash.com/photo-1611821064430-0d41043318e6?auto=format&fit=crop&q=80&w=800",
    type: "Coupe",
    featured: true,
    mostWanted: true,
    description: "Track weapon for the road. Weissach package included.",
    engine: "4000 cc",
    shipping: "By Air Shipping",
    status: "In Transit",
  },
  {
    make: "Rolls-Royce",
    model: "Cullinan",
    year: 2023,
    price: 2100000,
    mileage: 500,
    fuel: "Petrol",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1609520505218-7421da4c3c7c?auto=format&fit=crop&q=80&w=800",
    type: "SUV",
    featured: false,
    mostWanted: true,
    description: "The architecture of luxury. Bespoke interior.",
    engine: "6750 cc",
    shipping: "By Sea Shipping",
    status: "Available",
  },
  {
    make: "Lamborghini",
    model: "Huracan Evo",
    year: 2022,
    price: 950000,
    mileage: 4500,
    fuel: "Petrol",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1566024287286-457247b70310?auto=format&fit=crop&q=80&w=800",
    type: "Coupe",
    featured: false,
    mostWanted: false,
    description: "V10 naturally aspirated engine. Emotional sound.",
    engine: "5200 cc",
    shipping: "By Sea Shipping",
    status: "Sold",
  },
];
